課題 家具屋
codeschoolway/horiuchi pull request #2
Opened 2020-04-04 07:05 UTC by codeschoolway

# 初回コミット

2020-04-08 02:51 UTC, codeschoolway commented
## HomeページのHTML
73b2846 HomeページのHTMLを提出

2020-04-08 03:16 UTC, piasoratech requested changes
全体を通しての指摘としてclass名やid名に対して、省略した言葉を使用するのはやめましょう。
基本的に「誰が見ても意味を理解できる」名前にするのが基本です。
残りはコメントしたので確認をお願いします！

2020-04-08 03:16 UTC, piasoratech commented on html-kaguya/index.html
> +        <h1><a href="index.html">HTML<span>CSS</span></a></h1>
ここはロゴの画像があるのでそれを使用してください。

2020-04-08 03:16 UTC, piasoratech commented on html-kaguya/index.html
> +
`main`タグを使用しましょう

2020-04-08 03:16 UTC, piasoratech commented on html-kaguya/index.html
> +    <div id="home" class="big-bg">
`section`タグでない理由は何でしょうか？

2020-04-08 03:16 UTC, piasoratech commented on html-kaguya/index.html
> +                <p class="item-text">アームストロングのカウチ再入荷</p>
ここ課題と文章が違います

2020-04-08 03:16 UTC, piasoratech commented on html-kaguya/index.html
> +        <p class="btn"><a href="#">カタログをダウンロード</a></p>
ボタン用途なら別のタグを使用しましょう。

2020-04-08 03:16 UTC, piasoratech commented on html-kaguya/index.html
> +            <textarea id="message" name="your-message" tabindex="1" accesskey="a" placeholder="お問い合わせ内容">お問い合わせ内容</textarea>
初期値の設定は不要です。

2020-04-08 03:16 UTC, piasoratech commented on html-kaguya/index.html
> +        <div class="page-header">
`header`ではなく、`footer`では？

2020-04-08 06:45 UTC, codeschoolway commented
## HTML修正
cc02c4b
- 一部のclassやidを理解しやすい名前に変更
- ロゴの画像訂正
- タグ追加・変更
- テキスト修正　

2020-04-09 07:59 UTC, piasoratech approved these changes
良いかと！
次に進みましょう！

2020-04-09 16:11 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
指摘内容で同様に考えることができる部分は合わせて修正をお願いします

2020-04-09 16:11 UTC, piasoratech commented on html-kaguya/contact.html
> +        <div class="big-bg wrapper">
`section`でなく敢えて`div`を使った意図を教えていただきたいです。

2020-04-09 16:11 UTC, piasoratech commented on html-kaguya/news.html
> +                    <img class="item-img" src="images/AdobeStock_59829158_Preview.png" alt="">
`alt`タグを空文字にするのはその画像に意味がなく説明する文言がない時です。
今回の場合はある程度形容できると思うので、考えてみましょう。
ここで使っている3つの画像はいずれも同様です。

2020-04-09 16:11 UTC, piasoratech commented on html-kaguya/recruit.html
> +                        <h4>仕事内容</h4>
見出しではないので、hタグは使用せずに他のタグを使いましょう。
この`table`内すべて同様です。

2020-04-09 16:11 UTC, piasoratech commented on html-kaguya/recruit.html
> +                            <li>週３〜5日</li>
半全角そろえましょう

2020-04-09 23:05 UTC, codeschoolway commented on html-kaguya/contact.html
> +        <div class="big-bg wrapper">
`section`内では`p`のような意味のある内容が必要で`h`だけではそれに該当しないと思いましたがHTMLのドキュメントによると内容が必要という記述はないので`section`に変更しました。

2020-04-09 23:05 UTC, codeschoolway commented on html-kaguya/news.html
> +                    <img class="item-img" src="images/AdobeStock_59829158_Preview.png" alt="">
修正しました。

2020-04-09 23:05 UTC, codeschoolway commented on html-kaguya/recruit.html
> +                        <h4>仕事内容</h4>
`p`に変更しました。

2020-04-09 23:05 UTC, codeschoolway commented on html-kaguya/recruit.html
> +                            <li>週３〜5日</li>
半角にそろえました。

2020-04-10 02:37 UTC, piasoratech requested changes
半全角の話は数字のことを言っておりました。
失礼しました！
数字部分の修正をお願いします！

2020-04-10 04:21 UTC, piasoratech approved these changes
良いかと！
次進みましょう～

2020-04-13 05:56 UTC, piasoratech requested changes
・ここは画像位置が見本と比べてずれすぎているので修正しましょう
![image](https://user-images.githubusercontent.com/57445698/79095968-d0363000-7d96-11ea-8165-63e10fa5ec98.png)
・背景色？が変な感じになっています。
![image](https://user-images.githubusercontent.com/57445698/79095994-dfb57900-7d96-11ea-9b48-70bd1d92c855.png)

2020-04-13 06:49 UTC, codeschoolway commented
## Home CSS 修正

2020-04-13 07:37 UTC, piasoratech requested changes
・まだずれていますね…赤いチェアの真上にNEWSが来ると思うのですが…
　あとマークアップ時点で指摘漏れていて申し訳ないのですが、NEWSは全部大文字なので修正をお願いします。
![image](https://user-images.githubusercontent.com/57445698/79102121-0da1ba00-7da5-11ea-81c4-c2400b61f68e.png)

2020-04-13 09:07 UTC, piasoratech approved these changes
良いかと！

2020-04-14 03:44 UTC, piasoratech requested changes
・採用情報の表内の隙間見本にもう少し寄せましょう
![image](https://user-images.githubusercontent.com/57445698/79183871-a5f37980-7e4d-11ea-8e6d-bf60ec2ac685.png)

2020-04-14 04:27 UTC, codeschoolway commented
## Recruitページ CSS修正
recruitページのテーブル内ulを左に寄せる
76b1760

2020-04-14 05:27 UTC, piasoratech requested changes
左右ではなく、上下の意味合いで指摘していました。
分かりにくくて申し訳ありません。

2020-04-14 06:28 UTC, codeschoolway commented
## recuruitページの表内の余白を調整
91e4d23 recuruitページの表内の余白を調整

2020-04-14 06:31 UTC, piasoratech approved these changes
良いかと！
次に進みましょう！

2020-04-14 07:50 UTC, piasoratech requested changes
ブレークポイントをPCは1280px、スマホは375pxにしたうえで再提出お願いします

2020-04-14 09:58 UTC, piasoratech requested changes
・ヘッダーのロゴ部分画像が繰り返しになっているので確認をお願いします。(右端に微妙に見えている縦線はHの左側の縦線部分です。)
![image](https://user-images.githubusercontent.com/57445698/79205945-9427cb80-7e79-11ea-9d55-2c384459540a.png)
・全体を通して左側に余白があります。
![image](https://user-images.githubusercontent.com/57445698/79206060-c20d1000-7e79-11ea-8f5a-f75c627d657f.png)
・NEWS部分の画像がずれています。
![image](https://user-images.githubusercontent.com/57445698/79206126-d6e9a380-7e79-11ea-8a9f-85d32774f0dd.png)

2020-04-15 03:13 UTC, piasoratech requested changes
view moreのリンク先の設定をお願いします。
あと私のほうでは隙間がまだ空いているのですが、そちらではどうでしょうか？
確認の方法も含めて教えていただきたいです。

2020-04-15 04:43 UTC, codeschoolway commented
## 余白の修正など
fa53f32 全体的にある余白の修正

view moreは以前から実装されてますがそちらではご確認できない状態でしょうか。
<img width="816" alt="スクリーンショット 2020-04-15 13 21 10" src="https://user-images.githubusercontent.com/61524044/79298410-051fbf80-7f1c-11ea-9561-d3bf0a237d80.png">

隙間については以前にページ最上部と最下部のナビゲーションがモバイル表示時に横並びのまま画面から一部が飛び出し隙間ができたことがあったため、その時は`visibility: collapse`で非表示にしました。今回は`display: none` にして非表示にしました（style.css 366と426行目）。

> 要素を不可視にしてレイアウトから除去するには、 visibility を使用する代わりに display プロパティを none に設定してください。

https://developer.mozilla.org/ja/docs/Web/CSS/visibility

隙間の確認方法は画面上で行ってますが今回の修正前と後では画面上の変化はなく隙間はありません。こちらの画面では見た目での確認ができない状態です。
<img width="423" alt="スクリーンショット 2020-04-15 13 22 59" src="https://user-images.githubusercontent.com/61524044/79298847-4795cc00-7f1d-11ea-852c-e7fa2a930155.png">

2020-04-15 07:27 UTC, codeschoolway commented
## リンクの設定など
d7169b1 Homeのview moreにリンクを付けた
088b2a9 style.cssのモバイル表示の幅をmax-width: 100%に変更

余白を訂正しましたが、まだ訂正されていなければ具体的にどのような情報・数値をお伝えすればいいかお知らせください。
> 画面上の何で行っていて(おそらくデベロッパーツールを使用しているとは思いますが)、その時の数値設定はいくつになっているのでしょうか？
> 前提条件を共有いただかないことには何が原因なのかも判断がつかないので共有をお願いします。

2020-04-15 07:33 UTC, piasoratech requested changes
リンクについては修正OKですが、余白に関しては解決していません。
Slack側でやり取りさせてください

2020-04-15 09:05 UTC, codeschoolway commented
## ress.cssをプッシュしました
b65f876 ress.cssをプッシュ

2020-04-15 09:05 UTC, piasoratech approved these changes
見た目など指摘した部分はすべて解決していましたので、問題ありません

2020-04-16 03:29 UTC, piasoratech requested changes
・RECRUITの表が見本と異なるので、確認をお願いします
![image](https://user-images.githubusercontent.com/57445698/79411442-ceaa7900-7fdd-11ea-9eef-0a9ab9cd7aac.png)

2020-08-10 06:38 UTC, merged